# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - csc307-booktracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: npm install, build, and test
        run: |
          cd packages/express-backend
          npm install --prefix .
        env:
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
        working-directory: packages/express-backend

      - name: Zip artifact for deployment
        run: |
            cd packages/express-backend
            zip -r $GITHUB_WORKSPACE/release.zip *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Check zip contents
        run: unzip -l release.zip | head -30

      - name: npm install for deployment
        run: |
            cd packages/express-backend
            npm install --install-strategy=nested
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'csc307-booktracker'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2DF3CD8DD21B436494CCE108969507FB }}